version: '3.8'

services:
  main-app:
    build: .
    image: ct-annotation/main-app:latest
    ports:
      - "8000:8000"
    env_file:
      - .env
    environment:
      - FLASK_APP
      - FLASK_ENV
      - DATABASE_URL
      - SECRET_KEY
    depends_on:
      - db
    volumes:
      - .:/app
    command: sh -c "flask db upgrade && gunicorn --bind 0.0.0.0:8000 app.wsgi:app"

  db:
    image: postgres:15
    restart: always
    env_file:
      - .pgenv
    environment:
      - POSTGRES_USER
      - POSTGRES_PASSWORD
      - POSTGRES_DB
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata:
